### ISSUE TITLE
Merge all topics into one html

### ISSUE THREAD

**Issue by Billyshane** [infotexture/dita-bootstrap#50]
I have a map with small topics, so I want to merge them to one single html so that I can read it smothly. Is it possible to be realized in this plugin, please?

**Comment by jason-fox** [comment]
That sounds like a standard DITA [conref](https://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/conref.html) to me.

Instead of adding each  sub-`<topic>` directly into the ditamap like this:

#### Ditamap

```xml
<chapter format="dita" type="topic" href="audiobook/index.dita">
    <topicref navtitle="Install" format="dita" type="topic" href="audiobook/install.dita"/>
    <topicref navtitle="Usage" format="dita" type="topic" href="audiobook/usage.dita"/>
</chapter>
```

Use a `conref` and include your  sub-`<topic>` files as shown:

#### Ditamap

```xml
<chapter format="dita" type="topic" href="audiobook/index.dita"/>
```

#### Topic file

```xml
<topic id="install">
    <title>Install</title>
    <body>
        ... content goes here
    </body>
    <topic id="ffmpeg" conref="./ffmpeg.dita#ffmpeg">
        <title/>
        <body/>
    </topic>
    <topic id="text-to-speech" conref="./text-to-speech.dita#text-to-speech">
        <title/>
        <body/>
    </topic>
</topic>
```

An example can be found [here](https://jason-fox.github.io/dita-ot-plugins/audiobook/index.html), it uses the
`--nav-toc=nav-pill-scrollspy` and ` --menubar-toc.include=yes` build parameters to display a navigable [scrollspy](https://infotexture.github.io/dita-bootstrap/scrollspy.html) for the sub-topics.

**Comment by Billyshane** [comment]
Can I make changes in the plugin to take the whole map as one single topic?

**Comment by jason-fox** [comment]
Simple answer - no, not in the Bootstrap plugin.

More complex answer - the Bootstrap plugin is extending the default HTML5 plugin for rendering HTML. A template called `chapter-setup` is called on each  `<topic>`  found within the ditamap and each `<topic>`  file generates a separate file. If you wanted to mash everything into one file you would need to create **another plugin** and override **that** default behaviour before the Bootstrap plugin is called.

In my opinion, creating a single root topic full of [conref](https://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/conref.html)'d `<topic>` elements is the right way to go to do this, your topics remain small, isolated and reusable. Personally I would manually amend my existing topics if the document is not too big. If you already have a large codebase and you are looking to **generate** a conref'd stuffed single master `<topic>`, then you could automate this process by extending and overriding the [normalize plugin]( https://github.com/dita-ot/org.dita.normalize) somehow.

Whichever route you choose, it will not be the job of the Bootstrap plugin to do this - the Bootstrap plugin just deals with application of Bootstrap CSS classes to DITA elements and outputting of HTML as directed by other plugins further up the stack.
