### ISSUE TITLE
Missing breadcrumb when setting the "root-chunk-override" parameter.

### ISSUE THREAD

**Issue by Billy-102** [infotexture/dita-bootstrap#51]
After setting this parameter in the original html5 plugin:

![image](https://user-images.githubusercontent.com/94583069/187338503-9c3a782d-a03f-4e77-bb64-7b4a1e4a9c3a.png)

I found that the breadcrumb cannot be generated (I have made sure that the parameter "BREADCRUMBS" has been asigned with the value "yes"). Should I make some changes in the breadcrumb template? I would be very grateful if you can give some suggestions.

**Comment by jason-fox** [comment]
Generating HTML using 

```console
./dita -i ...   --args.breadcrumbs=yes --root-chunk-override=to-content
```
Doesn't really make sense, as you have stated that you are merging all `*.dita` files into one HTML, so there is no other HTML page for the breadcrumb to link to - this is why no breadcrumbs are generated.

The XSLT [breadcrumb.xsl](https://github.com/infotexture/dita-bootstrap/blob/develop/Customization/xsl/breadcrumb.xsl) is iterating through ancestors and displaying the `@href` if there is one. Also Line 49 is deliberately ignoring chunked content from the extra processing. If you want breadcrumbs for each of your sub-topics, you are going to have to add another `<xsl:when>` clause for chunks above line 41.

Instead of `--root-chunk-override=to-content` You could selectively add `chunk="to-content"` to parts of your map as shown. 

```xsl
<topicref href="parent1.dita"> 
      <topicref href="child1.dita" chunk="to-content"> 
        <topicref href="grandchild1.dita"/>
        <topicref href="grandchild2.dita"/>
      </topicref>
</topicref> 
```
