### ISSUE TITLE
Make list-group presentation for ToC optional

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap#6]
The latest changes apply the [Bootstrap List Group](https://getbootstrap.com/docs/5.0/components/list-group/) component style to the table of contents and embeds the full ToC in each page.

This approach works fine for small doc sets like the plugin's own docs, but doesn't scale well to publications that contain a large number of topics, where partial ToCs and standard unordered list presentation provide a better overview of the top-level items, and the current topic's place within that hierarchy.

We might want to consider adding a parameter that allows users to choose whether they want the ToC styled as a list group, or as a standard unordered list (which they can then style with custom CSS).

Another option might be to apply list group style when [nav-toc](https://www.dita-ot.org/dev/parameters/parameters-html5.html#html5__nav-toc)=`full`, but default to standard ULs when set to `partial`.

**Comment by jason-fox** [comment]
Both `nav-toc=full` and `nav-toc=partial` are already supported:

-  `nav-toc=full` - [DITA Project](https://github.com/jason-fox/dita-bootstrap/blob/feature/bootstrap-5.0/.github/dita-ot/html.xml#L21) - [Result](https://jason-fox.github.io/dita-bootstrap/index.html)
-  `nav-toc=partial` - [DITA Project](https://github.com/jason-fox/test-dita-build/blob/master/.github/dita-ot/html.xml#L21) [Result](https://jason-fox.github.io/test-dita-build/)

Since this is a standard build arg I didn't add anything to the **Using** section - it could make sense.

The default is set [here](https://github.com/infotexture/dita-bootstrap/blob/develop/build_dita2html5-bootstrap.xml#L26)

**Comment by infotexture** [comment]
Thanks, this looks like a good solution. 👍 

I know the default `full`/`partial` options worked before, it was the hard-coded list group formatting that struck me as something that might be less suitable for complex publications.

I'll test this on a few other projects, but since these changes preserve the ability to generate standard UL markup, I think it should be good.

**Comment by infotexture** [comment]
See #7 for implementation & additional comments.
