### ISSUE TITLE
Versioning strategy

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap#8]
Since [dita-ot/registry](https://github.com/dita-ot/registry) expects plug-ins to follow [semantic versioning](https://semver.org/) guidelines, the versions tagged in this repo thus far resemble SerVer conventions, but are actually a bit arbitrary.

### Background

When I prepared the first version for initial release a few years ago, I tagged it as `3.1` to reflect the DITA-OT version it was built for, and more or less stuck with that thereafter, with the exception of [3.4.1](https://github.com/infotexture/dita-bootstrap/releases/tag/3.4.1), which was a true maintenance release to incorporate a bugfix to the prior release.

Along the way, I considered switching the version numbers to reflect the bundled Bootstrap version instead of the supported DITA-OT version, but never actually switched.

### Upcoming versions

Two upcoming releases call this strategy into question:

- I'm currently in the process of backporting the initial 3.1 release for compatibility with DITA-OT 2.5.4.

  So far, I'm thinking of tagging this as `3.2` to indicate it's newer than the 3.1 release from which it's derived, yet does not include the Bootstrap 4 changes from plug-in version `3.3`. But if I stick to the target toolkit version scheme, I'd need to tag it as `2.5.4`.

- The volume of changes and new features from #4 would justify a significant version bump.

  The supported toolkit version here is likely the same as the current `3.6` release, so that previous versioning scheme would seem to break here. My impulse would be to bump the next version to 5.0 (or 5.0.x) to reflect the bundled Bootstrap version and the fact that it contains many new features when compared to `3.6`.

@jason-fox The next released version will contain your changes for Bootstrap 5.0. Any thoughts?

**Comment by jason-fox** [comment]
Since the `dita-bootstrap` is actual a **Bootstrap** plug-in for **DITA-OT**, I would suggest using **Bootstrap** as major version and **DITA-OT** as minor.

- Bootstrap 4.x for DITA-OT 2.x. = plug-in version  4.2.x
- Bootstrap 4.x for DITA-OT 3.x. = plug-in version 4.3.x
- Bootstrap 5.x for DITA-OT 2.x. = plug-in version  5.2.x
- Bootstrap 5.x for DITA-OT 3.x. = plug-in version  5.3.x

Eventually:

- Bootstrap 6.x for DITA-OT 3.x. = plug-in version  6.3.x
- Bootstrap 6.x for DITA-OT 4.x. = plug-in version  6.4.x
- etc.


The reasoning of aligning the major version with Bootstrap is that that will include bootstrap CSS `class` changes (which are DITA `outputclass` changes ) which means the tech writer will have to update their DITA files - this is a **major breaking change**

For backport to 2.5.4, there _may_ be a need to amend the XSL or ANT scripts, but that can be placed on a branch, the tech writer should just chose the correct plugin from the registry to align with their underlying DITA-OT engine - that should be a **minor change**

Obviously when Bootstrap 5 gets bug fixes the [`includes/bootstrap.hdf.xml`](https://github.com/infotexture/dita-bootstrap/blob/develop/includes/bootstrap.hdf.xml) file needs updating. There could also be bug fixes within the XSL to support a wider range of bootstrap widgets - that should be a **patch change**

**Comment by infotexture** [comment]
Thanks, good suggestion, I like that logic.

- It would work well for the upcoming releases, since all prior releases were tagged as “3._something_”
- A `5.3.x` release would be obviously newer
- My work-in-progress backport for Bootstrap 3.x & DITA-OT 2.x can be tagged as `3.2` 
  (I'll prepare that on a release branch that will **not** merge back to `master`)
