### ISSUE TITLE
Grid layout quirks

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap#89]
The new grid layout from Bootstrap 5.3 works well in most cases, but I've noticed a few minor issues we may want to resolve before releasing a new version of the plug-in.

## Narrow ToC area

The current grid layout leaves little room for the ToC (even at large desktop resolutions), so long headings often break to several lines. This clipping sometimes also affects the ToC link focus frame, which is cut off on the right edge:

<img width="997" alt="DITA-Bootstrap_ToC-focus-truncation@2x" src="https://github.com/infotexture/dita-bootstrap/assets/129995/4ac326da-e7e8-4391-9d1b-30db84286f53">

## Focus frame

🎗️ That focus frame seems to appear unnecessarily at times (rather than when invoked with `TAB`) but that's a separate issue.

## Empty right column

At desktop resolutions, the current grid layout includes an empty right column, presumably inherited from the Bootstrap docs layout, which uses that space for local _“On this page”_ navigation:

<img width="1280" alt="DITA-Bootstrap_empty-right-sidebar@2x" src="https://github.com/infotexture/dita-bootstrap/assets/129995/31888b55-8cae-414c-936b-0507e36bd901">

Since we don't generate that local navigation layer by default, it seems odd to reserve the space, particularly when the left ToC sidebar is so constrained.

I'm aware of the need to balance the layout on the page, and keep body content line lengths readable on large screens, but we can probably improve this a bit without breaking anything.

(I can look into these issues myself at some point, but I need to focus on the docs for DITA-OT 4.1 right now, so might not get to it until after that's released.)

**Comment by jason-fox** [comment]
a9a98b12 fixes the reserved whitespace. The relevant CSS should only be added if scrollspy is in use.

**Comment by jason-fox** [comment]
@infotexture - I think this can also be closed.

**Comment by infotexture** [comment]
While https://github.com/infotexture/dita-bootstrap/commit/a9a98b12fbbe27a3331873554b1ea1079f0969e9 fixes the whitespace reserved for the scroll spy navigation area per https://github.com/infotexture/dita-bootstrap/issues/89#issuecomment-1582237274, we might want to consider re-centering the content below the navigation header if no scroll spy ToC is enabled.

This happens automatically at larger desktop breakpoints, but we might want to use that same approach at earlier breakpoints to keep content and menu bar better aligned, and line lengths readable.

Note how menu bar width changes at various breakpoints, but content doesn't follow:

![DITA-Bootstrap-breakpoints](https://github.com/infotexture/dita-bootstrap/assets/129995/e011ce24-aeba-4010-a06d-0cffbe6e1a16)

**Comment by lakokkonen** [comment]
Another minor quirk is that at wider mobile screen sizes (when the TOC is collapsed), there is a considerable left margin in the content area:

![margin-inline](https://github.com/infotexture/dita-bootstrap/assets/108674366/9d9a6d70-83f4-430a-a699-edecfde34239)

It stems from the CSS setting a **max-width: 760px** and **margin-inline: auto** on **.bs-main**.

Not sure if this intentional, and it doesn't even look that bad, honestly. Just thought I'd mention it.

**Comment by infotexture** [comment]
Thanks to @lakokkonen for [reporting](https://github.com/infotexture/dita-bootstrap/issues/89#issuecomment-1862295287) and to @jason-fox for fixing this in #161. 🙏

**Comment by lakokkonen** [comment]
This is a closed issue, but continuing on this subject a bit:

I've experimented with adding a parameter that would let the user determine the size of the content container. The available options are the Bootstrap **container, container-fluid** and sized containers **sm-xxl**. That way the user could match the main layout's sizing and behaviour with the one on a custom header.

And by using **container-fluid** it would be easier to achieve a layout where the TOC is always on the left:

![img1](https://github.com/infotexture/dita-bootstrap/assets/108674366/2a8253dc-b08f-4217-9240-8c073a35af54)

The parameter also controls the size of the menubar-TOC, so that everything is aligned.

**Comment by jason-fox** [comment]
Sounds like a good idea - update`plugin.xml` and `insertParameters.xml` to add a new parameter and then add new `<xsl:param>` with the `select` matching the existing default to allow for overrides. I did something similar with `<note>` elements in #83

**Comment by lakokkonen** [comment]
@jason-fox Yes, that's how I got it working. And the default could be **container-xxl**, so everything should by default work as before.

Any preferences about the parameter name? Currently it's **content.container.size**.

I can do a pull request over the weekend at some point so you can check it out.

**Comment by jason-fox** [comment]
I'd go for something like `bootstrap.css.container.size` - most of the CSS parameters have a  `bootstrap.css.` prefix and as you said, its not just the `id="content"` which is the chapter body, but the parameter affects the Sub Menu as well (if present). 

I wouldn't change the  hard-coded defaults in the navbar includes, but may be add a comment line to

- `hdr.navbar.default.xml`
- `hdr.navbar.example.xml`
- `hdr.topbar.example.xml`

Explaining that they need to be changed if you alter the container size too.
